// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// eigen_chisq
float eigen_chisq(Eigen::VectorXi T1, Eigen::VectorXi T2, Eigen::VectorXi RowSum, int n);
RcppExport SEXP _rainette_eigen_chisq(SEXP T1SEXP, SEXP T2SEXP, SEXP RowSumSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type RowSum(RowSumSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_chisq(T1, T2, RowSum, n));
    return rcpp_result_gen;
END_RCPP
}
// eigen_split_tab
List eigen_split_tab(Eigen::MatrixXi tab, Eigen::VectorXi indices);
RcppExport SEXP _rainette_eigen_split_tab(SEXP tabSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_split_tab(tab, indices));
    return rcpp_result_gen;
END_RCPP
}
// eigen_switch_docs
Eigen::VectorXf eigen_switch_docs(Eigen::MatrixXi tab1, Eigen::MatrixXi tab2);
RcppExport SEXP _rainette_eigen_switch_docs(SEXP tab1SEXP, SEXP tab2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type tab1(tab1SEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type tab2(tab2SEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_switch_docs(tab1, tab2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rainette_eigen_chisq", (DL_FUNC) &_rainette_eigen_chisq, 4},
    {"_rainette_eigen_split_tab", (DL_FUNC) &_rainette_eigen_split_tab, 2},
    {"_rainette_eigen_switch_docs", (DL_FUNC) &_rainette_eigen_switch_docs, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rainette(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
