// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// eigen_chisq
float eigen_chisq(Eigen::VectorXi T1, Eigen::VectorXi T2, Eigen::VectorXi RowSum, int n);
RcppExport SEXP _rainette_eigen_chisq(SEXP T1SEXP, SEXP T2SEXP, SEXP RowSumSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type RowSum(RowSumSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_chisq(T1, T2, RowSum, n));
    return rcpp_result_gen;
END_RCPP
}
// eigen_split_tab_by_chisq
List eigen_split_tab_by_chisq(Eigen::MatrixXi tab, Eigen::VectorXi indices);
RcppExport SEXP _rainette_eigen_split_tab_by_chisq(SEXP tabSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXi >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_split_tab_by_chisq(tab, indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rainette_eigen_chisq", (DL_FUNC) &_rainette_eigen_chisq, 4},
    {"_rainette_eigen_split_tab_by_chisq", (DL_FUNC) &_rainette_eigen_split_tab_by_chisq, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rainette(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
