# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_colsums <- function(M) {
    .Call('_rainette_eigen_colsums', PACKAGE = 'rainette', M)
}

eigen_rowsums <- function(M) {
    .Call('_rainette_eigen_rowsums', PACKAGE = 'rainette', M)
}

eigen_chisq <- function(T1, T2, RowSum, n) {
    .Call('_rainette_eigen_chisq', PACKAGE = 'rainette', T1, T2, RowSum, n)
}

