# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_chisq <- function(T1, T2, RowSum, n) {
    .Call('_rainette_eigen_chisq', PACKAGE = 'rainette', T1, T2, RowSum, n)
}

eigen_split_tab_by_chisq <- function(tab, indices) {
    .Call('_rainette_eigen_split_tab_by_chisq', PACKAGE = 'rainette', tab, indices)
}

